### ISSUE TITLE
Error installing -  Cannot find module

### ISSUE THREAD

**Issue by subzero355** [miroslavpejic85/mirotalksfu#30]
```
npm start
```
gives
```
> mirotalksfu@1.0.0 start /home/milton/mirotalksfu
> node app/src/Server.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/milton/mirotalksfu/app/src/Server.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirotalksfu@1.0.0 start: `node app/src/Server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirotalksfu@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/milton/.npm/_logs/2021-12-19T12_26_04_751Z-debug.log

```

**Comment by miroslavpejic85** [comment]
Hello @subzero355, as the log says:

```bash
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
```

Before the npm start you need to install all the dependencies 

```bash
npm install
```

Did you follow all steps [here](https://github.com/miroslavpejic85/mirotalksfu#run-it-locally) ? 

Better would be to run it on Linux - Mac systems, as mediasoup might have some annoyance currently on Windows systems.

Regards

**Comment by subzero355** [comment]
Yes, I did npm install before npm start and I'm using Ubuntu 20.04

**Comment by subzero355** [comment]
log of ```npm install```
```
> mediasoup@3.9.2 postinstall /home/milton/mirotalksfu/node_modules/mediasoup
> node npm-scripts.js postinstall

npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: node npm-scripts.js worker:build
npm-scripts.js [INFO] running task "worker:build"
npm-scripts.js [INFO] executing command: make -C worker
make: Entering directory '/home/milton/mirotalksfu/node_modules/mediasoup/worker'
# Updated pip and setuptools are needed for meson
# `--system` is not present everywhere and is only needed as workaround for
# Debian-specific issue (copied from
# https://github.com/gluster/gstatus/pull/33), fallback to command without
# `--system` if the first one fails.
/usr/bin/python3 -m pip install --system --target=/home/milton/mirotalksfu/node_modules/mediasoup/worker/out/pip pip setuptools || \
        /usr/bin/python3 -m pip install --target=/home/milton/mirotalksfu/node_modules/mediasoup/worker/out/pip pip setuptools || \
        echo "Installation failed, likely because PIP is unavailable, if you are on Debian/Ubuntu or derivative please install the python3-pip package"
/usr/bin/python3: No module named pip
/usr/bin/python3: No module named pip
Installation failed, likely because PIP is unavailable, if you are on Debian/Ubuntu or derivative please install the python3-pip package
# Install `meson` and `ninja` using `pip` into custom location, so we don't
# depend on system-wide installation.
/usr/bin/python3 -m pip install --upgrade --target=/home/milton/mirotalksfu/node_modules/mediasoup/worker/out/pip  meson ninja
/usr/bin/python3: No module named pip
make: *** [Makefile:56: meson-ninja] Error 1
make: Leaving directory '/home/milton/mirotalksfu/node_modules/mediasoup/worker'
npm WARN notsup Unsupported engine for mediasoup@3.9.2: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: mediasoup@3.9.2
npm WARN mirotalksfu@1.0.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.9.2 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mediasoup@3.9.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-19T17_12_27_239Z-debug.log

```

**Comment by miroslavpejic85** [comment]
You're missing installing also : python3-pip DEB package - build-essential DEB package - python version >= 3.6 with PIP.

**Comment by subzero355** [comment]
yes my bad, overlooked the PIP error, now getting this with ```npm start```
```
> node app/src/Server.js

/home/milton/mirotalksfu/node_modules/mediasoup/node/lib/Logger.js:7
    #debug;
    ^

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/milton/mirotalksfu/node_modules/mediasoup/node/lib/index.js:4:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mirotalksfu@1.0.0 start: `node app/src/Server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mirotalksfu@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/milton/.npm/_logs/2021-12-19T17_15_54_565Z-debug.log
```

**Comment by subzero355** [comment]
my  bad again, I was using node 10.x, upgraded to 14.x and all good..

**Comment by miroslavpejic85** [comment]
Please make sure to have all requirement I read also in your preview logs:
```bash
Unsupported engine for mediasoup@3.9.2: wanted: {"node":">=12"} (current: {"node":"10.19.0","npm":"6.14.4"})
```
So install also node.js 12X or 14X.

**Comment by miroslavpejic85** [comment]
Well, we also wrote to each other at the same time :)
